name: Generate Datas

on:
  schedule:  # Execute every 12 hours
    - cron: "* */12 * * *"
  workflow_dispatch:  # Manually trigger the workflow

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest

    steps:
      # Step 1: Generate Snake Animation
      - name: Generate Snake Animation
        uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: gauravc21609  # Replace with your GitHub username
          svg_out_path: dist/github-contribution-grid-snake.svg  # Path to save the generated SVG file

      # Step 2: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output  # Replace with the branch you want to deploy to
          build_dir: dist  # Directory containing the generated files
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub token for authentication and deployment
